# Configuration for Knicks Seat Selector
# Copy this file to config.yaml and fill in your actual credentials

# SeatGeek API Configuration
# Get your credentials at: https://seatgeek.com/account/develop
# You'll receive both a Client ID and Client Secret
seatgeek:
  client_id: "YOUR_SEATGEEK_CLIENT_ID_HERE"
  client_secret: "YOUR_SEATGEEK_CLIENT_SECRET_HERE"

# Email Configuration
# For Gmail: You'll need to create an "App Password"
# Go to: https://myaccount.google.com/apppasswords
email:
  service: "gmail"              # Options: "gmail" or "smtp"
  email: "your-email@gmail.com" # Your email address
  password: "your-app-password"  # For Gmail, use App Password (not regular password)

  # For custom SMTP server (alternative to Gmail):
  # service: "smtp"
  # host: "smtp.example.com"
  # port: 587
  # secure: false

# Scheduler Configuration
scheduler:
  # Cron format: minute hour day-of-month month day-of-week
  # Default: "0 9 1 * *" runs at 9:00 AM on the 1st of every month
  cron: "0 9 1 * *"

  # Alternative schedules:
  # Weekly (every Monday at 9 AM): "0 9 * * 1"
  # Bi-weekly (1st and 15th at 9 AM): "0 9 1,15 * *"
  # Daily at 9 AM: "0 9 * * *"

# Recipient Emails (must match users in preferences.yaml)
# These will receive the monthly seat recommendations
recipients:
  - name: "Matt Diaz"
    email: "matt@example.com"
  - name: "Daniel"
    email: "daniel@example.com"
